# Generated by Django 5.2 on 2026-05-14 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('exitosa', 'Exitosa'), ('sin_resultado', 'Sin resultado'), ('error', 'Error')], default='exitosa', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='products.producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='stores.tienda')),
            ],
            options={
                'verbose_name': 'Consulta de precio',
                'verbose_name_plural': 'Consultas de precio',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_encontrado', models.CharField(max_length=255)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_efectivo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medio_pago', models.CharField(blank=True, default='', max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('url_producto', models.URLField(blank=True, default='', max_length=500)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='pricing.consultaprecio')),
            ],
            options={
                'verbose_name': 'Resultado encontrado',
                'verbose_name_plural': 'Resultados encontrados',
            },
        ),
        migrations.CreateModel(
            name='DecisionMejorPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('justificacion', models.TextField()),
                ('hubo_cambio', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='products.producto')),
                ('resultado_ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='pricing.resultadoencontrado')),
            ],
            options={
                'verbose_name': 'Decisión de mejor precio',
                'verbose_name_plural': 'Decisiones de mejor precio',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
