# Generated by Django 5.2 on 2026-05-19 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ok', 'Alerta enviada'), ('sin_cambio', 'Sin cambio de precio'), ('error', 'Error en el ciclo')], default='sin_cambio', max_length=20)),
                ('detalle', models.TextField(blank=True, default='', help_text='Mensaje adicional: descripción del error o razón del sin_cambio.')),
                ('decision', models.ForeignKey(blank=True, help_text='Decisión evaluada en este ciclo. Nula si hubo error antes de llegar a pricing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_monitoreo', to='pricing.decisionmejorprecio')),
            ],
            options={
                'verbose_name': 'Estado de monitoreo',
                'verbose_name_plural': 'Estados de monitoreo',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
