# Generated by Django 5.2 on 2026-05-19 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(help_text='Correo del destinatario.', max_length=254)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta de precio'), ('resumen', 'Resumen de estado')], default='alerta', max_length=10)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('error', 'Error')], default='enviado', max_length=10)),
                ('mensaje_error', models.TextField(blank=True, default='')),
                ('decision', models.ForeignKey(blank=True, help_text='Decisión que originó este correo. Nulo si es resumen general.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='pricing.decisionmejorprecio')),
            ],
            options={
                'verbose_name': 'Notificación de correo',
                'verbose_name_plural': 'Notificaciones de correo',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
